CREATE TABLE `tb_passport` (
  `uid` bigint(20) NOT NULL,
  `email` varchar(64) NOT NULL,
  `account` varchar(64) NOT NULL,
  `m_phone` varchar(64) NOT NULL,
  `password` varchar(32) NOT NULL,
  `actived` tinyint(1) NOT NULL DEFAULT '0',
  `number_account` bigint(20) DEFAULT NULL,
  `beauty_number` tinyint(1) DEFAULT NULL,
  `create_time` datetime NOT NULL,
  `pwd_question` varchar(100) DEFAULT '',
  `pwd_answer` varchar(50) DEFAULT NULL,
  `is_robot` tinyint(1) NOT NULL DEFAULT '0',
  `is_verified` tinyint(1) NOT NULL DEFAULT '0',
  `is_blacklisted` tinyint(1) NOT NULL DEFAULT '0',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `salt` varchar(36) DEFAULT NULL,
  `user_type` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`),
  UNIQUE KEY `uidx_email` (`email`),
  UNIQUE KEY `uidx_account` (`account`),
  UNIQUE KEY `uidx_mphone` (`m_phone`),
  UNIQUE KEY `uidx_numberaccount` (`number_account`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
