package com.ly.shard.ibatis.dao;

import com.ly.shard.ibatis.model.TbPassport;
import com.ly.shard.ibatis.model.TbPassportExample;
import java.util.List;

public interface TbPassportDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int countByExample(TbPassportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int deleteByExample(TbPassportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    void insert(TbPassport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    void insertSelective(TbPassport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    List selectByExample(TbPassportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    TbPassport selectByPrimaryKey(Long uid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int updateByExampleSelective(TbPassport record, TbPassportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int updateByExample(TbPassport record, TbPassportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int updateByPrimaryKeySelective(TbPassport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_passport
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    int updateByPrimaryKey(TbPassport record);
}