package com.ly.shard.ibatis.dao;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Component;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ly.shard.ibatis.model.TbPassport;
import com.ly.shard.ibatis.model.TbPassportExample;

@Component
public class TbPassportDAOImpl extends SqlMapClientDaoSupport implements TbPassportDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 * 
	 */

	@Autowired(required = true)
	@Qualifier("sqlMapClient")
	public void setSqlMapClientWorkaround(SqlMapClient sqlMapClient) {
		this.setSqlMapClient(sqlMapClient);
	}

	public TbPassportDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int countByExample(TbPassportExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tb_passport.ibatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int deleteByExample(TbPassportExample example) {
		int rows = getSqlMapClientTemplate().delete("tb_passport.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int deleteByPrimaryKey(Long uid) {
		TbPassport key = new TbPassport();
		key.setUid(uid);
		int rows = getSqlMapClientTemplate().delete("tb_passport.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public void insert(TbPassport record) {
		getSqlMapClientTemplate().insert("tb_passport.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public void insertSelective(TbPassport record) {
		getSqlMapClientTemplate().insert("tb_passport.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public List selectByExample(TbPassportExample example) {
		List list = getSqlMapClientTemplate().queryForList("tb_passport.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public TbPassport selectByPrimaryKey(Long uid) {
		TbPassport key = new TbPassport();
		key.setUid(uid);
		TbPassport record = (TbPassport) getSqlMapClientTemplate()
				.queryForObject("tb_passport.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int updateByExampleSelective(TbPassport record, TbPassportExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tb_passport.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int updateByExample(TbPassport record, TbPassportExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tb_passport.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int updateByPrimaryKeySelective(TbPassport record) {
		int rows = getSqlMapClientTemplate().update("tb_passport.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	public int updateByPrimaryKey(TbPassport record) {
		int rows = getSqlMapClientTemplate().update("tb_passport.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table tb_passport
	 *
	 * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
	 */
	private static class UpdateByExampleParms extends TbPassportExample {
		private Object record;

		public UpdateByExampleParms(Object record, TbPassportExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}