package com.ly.shard.ibatis.model;

import java.util.Date;

public class TbPassport {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.uid
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.email
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.account
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String account;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.m_phone
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String mPhone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.password
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.actived
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Boolean actived;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.number_account
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Long numberAccount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.beauty_number
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Boolean beautyNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.create_time
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.pwd_question
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String pwdQuestion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.pwd_answer
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String pwdAnswer;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.is_robot
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Boolean isRobot;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.is_verified
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Boolean isVerified;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.is_blacklisted
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Boolean isBlacklisted;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.is_deleted
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Boolean isDeleted;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.salt
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private String salt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_passport.user_type
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    private Integer userType;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.uid
     *
     * @return the value of tb_passport.uid
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.uid
     *
     * @param uid the value for tb_passport.uid
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.email
     *
     * @return the value of tb_passport.email
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.email
     *
     * @param email the value for tb_passport.email
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.account
     *
     * @return the value of tb_passport.account
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.account
     *
     * @param account the value for tb_passport.account
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.m_phone
     *
     * @return the value of tb_passport.m_phone
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getmPhone() {
        return mPhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.m_phone
     *
     * @param mPhone the value for tb_passport.m_phone
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setmPhone(String mPhone) {
        this.mPhone = mPhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.password
     *
     * @return the value of tb_passport.password
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.password
     *
     * @param password the value for tb_passport.password
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.actived
     *
     * @return the value of tb_passport.actived
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Boolean getActived() {
        return actived;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.actived
     *
     * @param actived the value for tb_passport.actived
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setActived(Boolean actived) {
        this.actived = actived;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.number_account
     *
     * @return the value of tb_passport.number_account
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Long getNumberAccount() {
        return numberAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.number_account
     *
     * @param numberAccount the value for tb_passport.number_account
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setNumberAccount(Long numberAccount) {
        this.numberAccount = numberAccount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.beauty_number
     *
     * @return the value of tb_passport.beauty_number
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Boolean getBeautyNumber() {
        return beautyNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.beauty_number
     *
     * @param beautyNumber the value for tb_passport.beauty_number
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setBeautyNumber(Boolean beautyNumber) {
        this.beautyNumber = beautyNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.create_time
     *
     * @return the value of tb_passport.create_time
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.create_time
     *
     * @param createTime the value for tb_passport.create_time
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.pwd_question
     *
     * @return the value of tb_passport.pwd_question
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getPwdQuestion() {
        return pwdQuestion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.pwd_question
     *
     * @param pwdQuestion the value for tb_passport.pwd_question
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setPwdQuestion(String pwdQuestion) {
        this.pwdQuestion = pwdQuestion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.pwd_answer
     *
     * @return the value of tb_passport.pwd_answer
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getPwdAnswer() {
        return pwdAnswer;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.pwd_answer
     *
     * @param pwdAnswer the value for tb_passport.pwd_answer
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setPwdAnswer(String pwdAnswer) {
        this.pwdAnswer = pwdAnswer;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.is_robot
     *
     * @return the value of tb_passport.is_robot
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Boolean getIsRobot() {
        return isRobot;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.is_robot
     *
     * @param isRobot the value for tb_passport.is_robot
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setIsRobot(Boolean isRobot) {
        this.isRobot = isRobot;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.is_verified
     *
     * @return the value of tb_passport.is_verified
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Boolean getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.is_verified
     *
     * @param isVerified the value for tb_passport.is_verified
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.is_blacklisted
     *
     * @return the value of tb_passport.is_blacklisted
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Boolean getIsBlacklisted() {
        return isBlacklisted;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.is_blacklisted
     *
     * @param isBlacklisted the value for tb_passport.is_blacklisted
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setIsBlacklisted(Boolean isBlacklisted) {
        this.isBlacklisted = isBlacklisted;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.is_deleted
     *
     * @return the value of tb_passport.is_deleted
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.is_deleted
     *
     * @param isDeleted the value for tb_passport.is_deleted
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.salt
     *
     * @return the value of tb_passport.salt
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.salt
     *
     * @param salt the value for tb_passport.salt
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_passport.user_type
     *
     * @return the value of tb_passport.user_type
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_passport.user_type
     *
     * @param userType the value for tb_passport.user_type
     *
     * @ibatorgenerated Tue Aug 09 17:38:14 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
}